### ISSUE TITLE
Timming problems?

### ISSUE THREAD

**Issue by victorsndvg** [vsoch/singularity-python#4]
I'm installing master branch of sregistry, and also development brach of singularity-python (native not container).

Trying to push to the SRegistry I get the following log:
```
uwsgi_1   | [pid: 49|app: 0|req: 32/32] 10.38.3.43 () {40 vars in 757 bytes} [Fri Oct 27 07:43:04 2017] POST /api/push/ => generated 25 bytes in 434 msecs (HTTP/1.1 403) 5 headers in 162 bytes (1 switches on core 0)
uwsgi_1   | DEBUG push/YmFycmFjdWRh/20171027T14Z
uwsgi_1   | DEBUG 20171027T14Z is expired, must be 20171027T07Z.
uwsgi_1   | [pid: 49|app: 0|req: 33/33] 10.38.3.43 () {40 vars in 757 bytes} [Fri Oct 27 07:43:26 2017] POST /api/push/ => generated 25 bytes in 459 msecs (HTTP/1.1 403) 5 headers in 162 bytes (1 switches on core 0)
```
Any idea?

**Comment by vsoch** [comment]
I think you already brought this issue up, and we discussed that it's the derivation of the date / time in python 2 vs. 3, and I suggested you use the container.

**Comment by vsoch** [comment]
https://github.com/vsoch/singularity-python/issues/2#issuecomment-338601946

**Comment by victorsndvg** [comment]
This happens with python 3.6 (miniconda) and singularity-python installed natively.

The container returns another error ... but now I'm not in front of my computer

**Comment by vsoch** [comment]
oh interesting - are you absolutely sure you are using the correct sregistry executable? Can you show the output of `which sregistry` ?

**Comment by vsoch** [comment]
when you get back to your computer of course :)

**Comment by victorsndvg** [comment]
I'm back!

Here is the requested information:
```
$ which sregistry 
/usr/local/bin/sregistry
$ /usr/local/bin/sregistry --version
1.2.1
$ python --version
Python 3.6.3 :: Anaconda, Inc.
```

**Comment by vsoch** [comment]
I think this confirms there is a mismatch - your sregistry binary is located in a system location (where python 2.x usually is) but your python is anaconda, which is usually at $HOME/anaconda3 (or other) but unlikely to be under /iusr/local. Please try removing the top sregistry **And** doing pip an pip3 uninstall singularity, then reinstall making sure you target the anaconda python (eg, python -m pip install singularity) and then please report the location of the sregistry binary. Thanks!

**Comment by victorsndvg** [comment]
Sorry, I'm confused here.

I'm using `python3.6` from anaconda, but installed in system directories. In particular in `/usr/local/lib/python3.6/`

Doing a search of any random package included in the `singularity-python` requirements, I can get the following output:
```
$ find /usr/ -name *dateutil*
/usr/local/lib/python3.6/site-packages/python_dateutil-2.6.1.dist-info
/usr/local/lib/python3.6/site-packages/dateutil
/usr/local/lib/python3.6/site-packages/dateutil/zoneinfo/dateutil-zoneinfo.tar.gz
```
or with the `singularity-python` stuff:
```
$ find /usr/ -name *singularity-1.2.1*
/usr/local/lib/python3.6/site-packages/singularity-1.2.1-py3.6.egg
```
There is a single coincidence under the `python3.6` hierarchy. Nothing in `/usr/local/lib/python2.7/`

I tried to uninstall and reinstall, but I'm getting exactly the same. I think I'm not using nothing from `python2.7`, but maybe I'm wrong ...

I'm missing something?

**Comment by vsoch** [comment]
okay I was able to reproduce the error! I'm looking into it now.

One quick question - the default client compresses the image, but this isn't necessary given squashfs. Are you using Singularity 2.4 or a previous version? I think I'd like to make the default to not compress (assume squashfs), but am interested in your thoughts.

**Comment by vsoch** [comment]
Ok here is with the current (fresh build) of sregistry (on the right) and the client image (left) the import of the same function is producing a different timestamp, so it's a version issue. 

![image](https://user-images.githubusercontent.com/814322/32173651-f30116ee-bd3c-11e7-901a-a95b8618f2d9.png)

So I just pushed some changes to singularity-python (vsoch branch) development that testing locally seemed to work, I will likely not merge them into the main branch until a little more testing, but as a workaround you can use those branches, or it comes down to changing this function in singularity.registry.auth:

```
from datetime import datetime, timezone

def generate_timestamp():
    ts = datetime.now(timezone.utc)
    return ts.strftime('%Y%m%dT%HZ')
```
Sorry about this, I feel like I fixed this issue and it got lost somewhere...

**Comment by victorsndvg** [comment]
Hi @vsoch ,

Now we are using Singularity 2.3, but I think in the future we will only use Singularity >= 2.4.

I will try your changes ASAP.

Thanks!

**Comment by victorsndvg** [comment]
Hi @vsoch,

It still don't works.  The same error appear in the log messages.
```
uwsgi_1   | DEBUG 20171031T09Z is expired, must be 20171031T04Z.
```
I was trying to follow the flow of the timestamp, but I'm lost.

I can confirm:
- Executing the following python in local host and worker and uwsgi images returns the same (`20171031T09Z`):
```
from datetime import datetime, timezone
ts = datetime.now(timezone.utc)
print(ts.strftime('%Y%m%dT%HZ'))
```
- Printing the time on the client side in `generate_timestamp()` returns `20171031T09Z`
- Printing the full `auth` in `validate_request()` returns `20171031T09Z`

In this case the log messages look like:
```
uwsgi_1   | DEBUG push/dmljdG9yc25kdmc=/20171031T09Z
uwsgi_1   | DEBUG SREGISTRY-HMAC-SHA256 Credential=push/dmljdG9yc25kdmc=/20171031T09Z,Signature=1cc8810db8a1782b7bee8970c7f216a64b368f0574d1675f018d47d2d017e134
uwsgi_1   | DEBUG 20171031T09Z is expired, must be 20171031T04Z.
uwsgi_1   | [pid: 49|app: 0|req: 4/4] 10.38.3.98 () {40 vars in 761 bytes} [Tue Oct 31 04:34:48 2017] POST /api/push/ => generated 25 bytes in 625 msecs (HTTP/1.1 403) 5 headers in 162 bytes (1 switches on core 0)
```
I don't know where the `20171031T04Z` timestamp come from!  hahaha

Can you help me to debug this?

**Comment by vsoch** [comment]
I think your images (uwsgi and worker) probably have the old version of singularity python! Even if you rebuild with docker it would use the cache. So try shelling inside, first do `pip uninstall singularity` multiple times until you get the message it's not installed, and then clone the repo development branch, and reinstall. Then exit, do docker-compose restart, and try again! So it will look something like this, for each of worker and uwsgi

```
# Shell into uwsgi
docker exec -it <containerid> bash
pip uninstall singularity
pip uninstall singularity...
# until it tells you not installed
cd /tmp && git clone -b development https://www.github.com/vsoch/singularity-python
cd singularity-python && python setup.py install
exit

# Now do the same for worker
exit

docker-compose restart
```
then try again

**Comment by victorsndvg** [comment]
I think my images are up-to-date. I perform a new installation from scratch in a new Ubuntu 16.0 VM

**Comment by vsoch** [comment]
I really like that install script! Do you want to get it working as you like and PR to add somewhere as an example? 

The Dockerfile for sregistry uses requirements.txt to reference an old commit:

```
-e git+https://github.com/vsoch/singularity-python.git@development#egg=singularity
```

I have not had a chance to update it, so could you please try the commands I specified to update the software in the image and retry? We can update the commit in requirements.txt when you have confirmed it looks a-ok. Thanks!

**Comment by victorsndvg** [comment]
Hi, 

sorry where I have to put this? 

I suppose I have to replace:
`pip install -r requirements`
by
`pip install -e git+https://github.com/vsoch/singularity-python.git@development#egg=singularity`

I'm right?

Do you really want to put this script into the `sregistry` repo (or another one)?
It's an ad-hoc installation script for Ubuntu 16.04, not a generic one ... But I can create a PR if you want!

**Comment by vsoch** [comment]
The commands are run in the image, interactively. When we update sregistry we will update the requirements.txt file, and there wouldn't be needed to add pip install (as you've shown above) you direct it att he entire file.

**Comment by victorsndvg** [comment]
sorry for the delay @vsoch , I was on holidays.

I try to perform a clean installation using the script and changing the `git clone` command of `sregistry` repository to work with the new `update/singularity-python` branch, but the problem persists ...

I think I'm doing something wrong, but I'm not able to discover the error...

Any Idea about how to proceed?

**Comment by vsoch** [comment]
Hey @victorsndvg ! I just did very detailed testing and the functions / versions from singularity python were correct... but I was importing from utils! Derp. So I just updated and here are my steps to show working, so sorry about this!
```
git branch
  dctrud-ldap_auth
  ldap_auth
  master
  paper/update
* update/singularity-python
  victorsndvg-patch-1

docker build --no-cache -t vanessa/sregistry .
```
Then build the sregistry image

```
sudo singularity build sregistry.simg Singularity
```

then bring up the images, and quickly logged into the web UI and added myself as a user and admin:

```
docker-compose up -d
```

Then here is the push!

```
sregistry --debug push --name hallo/moto sregistry 
[================================] 795/795 MB - 00:00:00
Upload finished! [Return status 201 Created]
```

**Comment by victorsndvg** [comment]
Perfect! 

`push` works updating `update/singularity-python` branch! :clap: :clap: 

Thanks!
